### ISSUE TITLE
关于baseline精度问题

### ISSUE THREAD

**Issue by zylprivate** [xjtushujun/meta-weight-net#11]
请问baseline 的参数设置和其他方法的设置一样吗，为什么baseline在噪声40%的结果偏高呢，大约0.8左右

**Comment by zylprivate** [comment]
实验细节 在arxiv的支撑材料里，baseline 随着epoch 的增加会过拟合这些噪声。不过baseline 结合 early-stop 也能取得很好的效果。

**Comment by zylprivate** [comment]
> I got the same problem, could the author clarify? Much appreciated

实验细节 在arxiv的支撑材料里，baseline 随着epoch 的增加会过拟合这些噪声。不过baseline 结合 early-stop 也能取得很好的效果。

**Comment by pipilurj** [comment]
感谢回答，我跑baseline一样的epoch数，貌似也没有出现overfit的现象
