### ISSUE TITLE
关于模型的问题

### ISSUE THREAD

**Issue by zhaoxin94** [xjtushujun/meta-weight-net#5]
首先，非常感谢你们开源这么优秀的工作！

我有一个疑惑，为什么作者重写了整个模型。

基于MetaModule重写了所有卷积，线性和批量归一化的目的是什么呢？为什么不直接使用torch.nn模块里的模型（如，nn.Conv2d），就如同pytorch官方实现的resnet等。

**Comment by PyJulie** [comment]
同问，这个问题请问解决了吗，求告知
